<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>BSW Radio</title>
    <link rel="stylesheet" type="text/css" href="./assets/plugin/css/style.css">
    <link rel="stylesheet" type="text/css" href="./assets/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="./assets/css/demo.css">
    <script type="text/javascript" src="./assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="./assets/plugin/jquery-jplayer/jquery.jplayer.js"></script>
    <script type="text/javascript" src="./assets/plugin/ttw-music-player-min.js"></script>    
    <script type="text/javascript" src="./assets/js/fancywebsocket.js"></script>
    <script type="text/javascript" src="./assets/js/webrtc.js"></script>

    <script type="text/javascript">

        // Configs
        var server_name = 'ws://' + location.hostname + ':9301';
        var pusher_config = { key: '<?= $app_key ?>',  channel: '<?= $app_channel ?>' };
        var dj_ip = '<?= $dj_ip; ?>';
        var current_song = '<?= $current_song; ?>';
        var message_of_the_day = '<?= $message_of_the_day; ?>';
        var myPlaylist = [];

        <?php 
            
        foreach ( $playlist as $key => $value) {

            ?>

            myPlaylist.push({
                mp3:"<?php echo $value['mp3'] ?>",
                oga:'mix/1.ogg',
                title:"<?php echo $value['title'] ?>",
                artist:"<?php echo $value['artist'] ?>",
                rating:4,
                buy:'#',
                price:'1.00',
                duration:'0:30',
                cover:"<?php echo $value['png'] ?>"
            });

            <?php
     
        }

        ?>        

    </script>
    <script src="//js.pusher.com/2.2/pusher.min.js"></script>   
</head>
<body>
    <div id="title">BSW Web Radio</div>
    <div id="message_of_the_day">
        <label class="text-grey pull-left full-width">Set DJ message:</label>
        <textarea class="message pull-left full-width" rows="3"></textarea>
        <button id="update_mod">Update</button>

        <label class="text-grey pull-left full-width">DJ Question of the day:</label>
        <div class="preview pull-left full-width text-grey mod"><?= $message_of_the_day ?></div>
    </div>
    <textarea id="log" name="log" readonly="readonly"></textarea>
    <script src="./assets/js/script.js"></script>

</body>
</html>